use std::path::Path;

use super::types::{
    ActivationConfig, ArtifactFormat, ConversionLane, KeyboardShortcut, Modality, ModelManifest,
    RuntimeKind, WakeWordConfigItem,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WakeCommandDefinition {
    pub command_key: &'static str,
    pub phrase: &'static str,
    pub model_filename: &'static str,
    pub threshold: u32,
    pub aliases: &'static [&'static str],
}

const LIVEKIT_WAKE_THRESHOLD_PERCENT: u32 = 68;

const WAKE_COMMAND_DEFINITIONS: [WakeCommandDefinition; 5] = [
    WakeCommandDefinition {
        command_key: "dx",
        phrase: "dx",
        model_filename: "dx.onnx",
        threshold: LIVEKIT_WAKE_THRESHOLD_PERCENT,
        aliases: &[],
    },
    WakeCommandDefinition {
        command_key: "friday",
        phrase: "friday",
        model_filename: "friday.onnx",
        threshold: LIVEKIT_WAKE_THRESHOLD_PERCENT,
        aliases: &[],
    },
    WakeCommandDefinition {
        command_key: "hello",
        phrase: "hello",
        model_filename: "hello.onnx",
        threshold: LIVEKIT_WAKE_THRESHOLD_PERCENT,
        aliases: &[],
    },
    WakeCommandDefinition {
        command_key: "aladdin",
        phrase: "aladdin",
        model_filename: "aladdin.onnx",
        threshold: LIVEKIT_WAKE_THRESHOLD_PERCENT,
        aliases: &[],
    },
    WakeCommandDefinition {
        command_key: "arise",
        phrase: "arise",
        model_filename: "arise.onnx",
        threshold: LIVEKIT_WAKE_THRESHOLD_PERCENT,
        aliases: &[],
    },
];

pub fn wake_command_definitions() -> &'static [WakeCommandDefinition] {
    &WAKE_COMMAND_DEFINITIONS
}

fn manifest(
    key: &str,
    display_name: &str,
    family: &str,
    repo_id: &str,
    modality: Modality,
    local_path: Option<&str>,
    artifact_format: ArtifactFormat,
    preferred_runtime: RuntimeKind,
    fallback_runtimes: &[RuntimeKind],
    conversion_lanes: &[ConversionLane],
    minimum_memory_bytes: u64,
    quantization: Option<&str>,
    license: Option<&str>,
    redistributable: bool,
    gated: bool,
    local_only: bool,
    tags: &[&str],
) -> ModelManifest {
    ModelManifest {
        key: key.to_string(),
        display_name: display_name.to_string(),
        family: family.to_string(),
        repo_id: repo_id.to_string(),
        modality,
        local_path: local_path.map(str::to_string),
        artifact_format,
        preferred_runtime,
        fallback_runtimes: fallback_runtimes.to_vec(),
        conversion_lanes: conversion_lanes.to_vec(),
        minimum_memory_bytes,
        quantization: quantization.map(str::to_string),
        license: license.map(str::to_string),
        redistributable,
        gated,
        local_only,
        tags: tags.iter().map(|tag| (*tag).to_string()).collect(),
    }
}

pub fn default_model_catalog() -> Vec<ModelManifest> {
    vec![
        manifest(
            "qwen3-0.6b",
            "Qwen3 0.6B",
            "Qwen3",
            "Qwen/Qwen3-0.6B",
            Modality::Chat,
            Some("models/llm/Qwen3-0.6B-Q4_K_M.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::MistralRsEmbedded, RuntimeKind::CandleEmbedded],
            &[ConversionLane::Gguf, ConversionLane::NativeSafetensors],
            6 * 1024 * 1024 * 1024,
            Some("Q4_K_M"),
            Some("apache-2.0"),
            true,
            false,
            false,
            &[
                "low-end",
                "text",
                "default",
                "helper",
                "prompt-enhancer",
                "text-converter",
                "fastest",
            ],
        ),
        manifest(
            "qwen3.5-2b",
            "Qwen3.5 2B",
            "Qwen3.5",
            "Qwen/Qwen3.5-2B",
            Modality::Chat,
            Some("models/llm/Qwen3.5-2B-Q4_K_M.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::MistralRsEmbedded, RuntimeKind::CandleEmbedded],
            &[ConversionLane::Gguf, ConversionLane::NativeSafetensors],
            8 * 1024 * 1024 * 1024,
            Some("Q4_K_M"),
            Some("apache-2.0"),
            true,
            false,
            false,
            &["balanced", "text"],
        ),
        manifest(
            "qwen35-9b-q4km",
            "Qwen3.5 9B Q4_K_M",
            "Qwen3.5",
            "jc-builds/Qwen3.5-9B-Q4_K_M-GGUF",
            Modality::Chat,
            Some("models/llm/Qwen3.5-9B-Q4_K_M.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::MistralRsEmbedded, RuntimeKind::CandleEmbedded],
            &[ConversionLane::Gguf, ConversionLane::NativeSafetensors],
            18 * 1024 * 1024 * 1024,
            Some("Q4_K_M"),
            Some("apache-2.0"),
            true,
            false,
            false,
            &[
                "coding",
                "local-coding",
                "typescript",
                "react",
                "tailwind",
                "shadcn",
                "dx-ui",
                "recommended-coding",
            ],
        ),
        manifest(
            "qwen35-4b-revised-q4km",
            "Qwen3.5 4B Revised Q4_K_M",
            "Qwen3.5",
            "Smoffyy/Qwen3.5-4B-Instruct-Revised-GGUF",
            Modality::Chat,
            Some("models/llm/Qwen3.5-4B-q4_k_m.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::MistralRsEmbedded, RuntimeKind::CandleEmbedded],
            &[ConversionLane::Gguf, ConversionLane::NativeSafetensors],
            12 * 1024 * 1024 * 1024,
            Some("Q4_K_M"),
            Some("apache-2.0"),
            true,
            false,
            false,
            &[
                "coding",
                "local-coding",
                "typescript",
                "react",
                "tailwind",
                "shadcn",
                "dx-ui",
                "speed-quality",
                "daily-smart",
                "quality-chat",
                "recommended-coding",
                "default-coding",
            ],
        ),
        manifest(
            "xlam2-3b-fc-r-q4km",
            "xLAM-2 3B Function Calling Q4_K_M",
            "xLAM-2",
            "Salesforce/xLAM-2-3b-fc-r-gguf",
            Modality::Chat,
            Some("models/llm/xLAM-2-3B-fc-r-Q4_K_M.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::MistralRsEmbedded, RuntimeKind::CandleEmbedded],
            &[ConversionLane::Gguf],
            8 * 1024 * 1024 * 1024,
            Some("Q4_K_M"),
            Some("cc-by-nc-4.0"),
            false,
            false,
            false,
            &[
                "tool-calling",
                "function-calling",
                "agent",
                "json",
                "research-only",
                "recommended-tool-research",
            ],
        ),
        manifest(
            "ministral3-3b-instruct-q4km",
            "Ministral 3 3B Instruct Q4_K_M",
            "Ministral 3",
            "unsloth/Ministral-3-3B-Instruct-2512-GGUF",
            Modality::Chat,
            Some("models/llm/Ministral-3-3B-Instruct-2512-Q4_K_M.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::MistralRsEmbedded, RuntimeKind::CandleEmbedded],
            &[ConversionLane::Gguf],
            10 * 1024 * 1024 * 1024,
            Some("Q4_K_M"),
            Some("apache-2.0"),
            true,
            false,
            false,
            &[
                "tool-calling",
                "function-calling",
                "agent",
                "json",
                "reasoning",
                "quality-chat",
                "commercial-safe",
                "recommended-tool-commercial",
            ],
        ),
        manifest(
            "granite4-h-micro-q4km",
            "Granite 4.0 H Micro Q4_K_M",
            "Granite 4.0",
            "ibm-granite/granite-4.0-h-micro-GGUF",
            Modality::Chat,
            Some("models/llm/granite-4.0-h-micro-Q4_K_M.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::MistralRsEmbedded, RuntimeKind::CandleEmbedded],
            &[ConversionLane::Gguf],
            8 * 1024 * 1024 * 1024,
            Some("Q4_K_M"),
            Some("apache-2.0"),
            true,
            false,
            false,
            &[
                "tool-calling",
                "function-calling",
                "agent",
                "json",
                "structured-output",
                "commercial-safe",
                "router",
            ],
        ),
        manifest(
            "phi4-mini-instruct-q4km",
            "Phi-4 Mini Instruct Q4_K_M",
            "Phi-4",
            "DuoNeural/Phi-4-mini-instruct-GGUF",
            Modality::Chat,
            Some("models/llm/Phi-4-mini-instruct-Q4_K_M.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::MistralRsEmbedded, RuntimeKind::CandleEmbedded],
            &[ConversionLane::Gguf],
            10 * 1024 * 1024 * 1024,
            Some("Q4_K_M"),
            Some("mit"),
            true,
            false,
            false,
            &[
                "tool-calling",
                "function-calling",
                "reasoning",
                "commercial-safe",
                "long-context",
            ],
        ),
        manifest(
            "smollm3-3b-q4km",
            "SmolLM3 3B Q4_K_M",
            "SmolLM3",
            "ggml-org/SmolLM3-3B-GGUF",
            Modality::Chat,
            Some("models/llm/SmolLM3-Q4_K_M.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::MistralRsEmbedded, RuntimeKind::CandleEmbedded],
            &[ConversionLane::Gguf],
            8 * 1024 * 1024 * 1024,
            Some("Q4_K_M"),
            Some("apache-2.0"),
            true,
            false,
            false,
            &[
                "small",
                "fast",
                "reasoning",
                "long-context",
                "commercial-safe",
            ],
        ),
        manifest(
            "gemma4-e2b-q8",
            "Gemma 4 E2B Q8",
            "Gemma 4",
            "google/gemma-4-e2b-it",
            Modality::Chat,
            Some("models/llm/gemma-4-E2B-it-Q8_0.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::CandleEmbedded, RuntimeKind::MistralRsEmbedded],
            &[ConversionLane::Gguf, ConversionLane::NativeSafetensors],
            12 * 1024 * 1024 * 1024,
            Some("Q8_0"),
            Some("gemma"),
            true,
            false,
            false,
            &["multimodal-ready", "balanced"],
        ),
        manifest(
            "gemma4-e4b-frontend-text-q4km",
            "Gemma 4 E4B Frontend Q4_K_M (text)",
            "Gemma 4 Frontend",
            "DuoNeural/Gemma-4-E4B-Frontend-GGUF",
            Modality::Chat,
            Some("models/llm/gemma-4-E4B-it.Q4_K_M.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::MistralRsEmbedded, RuntimeKind::CandleEmbedded],
            &[ConversionLane::Gguf],
            18 * 1024 * 1024 * 1024,
            Some("Q4_K_M"),
            Some("apache-2.0"),
            true,
            false,
            false,
            &[
                "frontend",
                "coding",
                "react",
                "vue",
                "tailwind",
                "shadcn",
                "text-only-benchmark",
                "ui-eval",
                "avoid-daily-chat",
            ],
        ),
        manifest(
            "gemma4-e4b-frontend-q4km",
            "Gemma 4 E4B Frontend Q4_K_M + BF16 mmproj",
            "Gemma 4 Frontend",
            "DuoNeural/Gemma-4-E4B-Frontend-GGUF",
            Modality::VisionLanguage,
            Some("models/llm/gemma-4-E4B-it.Q4_K_M.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::CandleEmbedded, RuntimeKind::MistralRsEmbedded],
            &[ConversionLane::Gguf],
            18 * 1024 * 1024 * 1024,
            Some("Q4_K_M + BF16-mmproj"),
            Some("apache-2.0"),
            true,
            false,
            false,
            &[
                "ui",
                "vision",
                "image-text-to-text",
                "frontend",
                "react",
                "vue",
                "tailwind",
                "screenshot-to-code",
                "recommended-next",
            ],
        ),
        manifest(
            "webgen-4b-preview-i1-q4km",
            "WEBGEN 4B Preview i1 Q4_K_M",
            "WEBGEN",
            "mradermacher/WEBGEN-4B-Preview-i1-GGUF",
            Modality::UiGeneration,
            Some("models/llm/WEBGEN-4B-Preview.i1-Q4_K_M.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::MistralRsEmbedded, RuntimeKind::CandleEmbedded],
            &[ConversionLane::Gguf],
            10 * 1024 * 1024 * 1024,
            Some("Q4_K_M"),
            Some("apache-2.0"),
            true,
            false,
            false,
            &[
                "ui",
                "web-generation",
                "frontend",
                "html",
                "css",
                "tailwind",
                "google-eval-candidate",
            ],
        ),
        manifest(
            "qwendean-4b-q4km",
            "Qwendean 4B Q4_K_M",
            "Qwendean",
            "iamdyeus/qwendean-4b-GGUF",
            Modality::UiGeneration,
            Some("models/llm/Qwendean-4B.Q4_K_M.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::MistralRsEmbedded, RuntimeKind::CandleEmbedded],
            &[ConversionLane::Gguf],
            10 * 1024 * 1024 * 1024,
            Some("Q4_K_M"),
            Some("apache-2.0"),
            true,
            false,
            false,
            &[
                "ui",
                "react",
                "typescript",
                "shadcn",
                "frontend",
                "google-eval-candidate",
            ],
        ),
        manifest(
            "uigen-fx-4b-preview-q4km",
            "UIGEN-FX 4B Preview Q4_K_M",
            "UIGEN-FX",
            "QuantFactory/UIGEN-FX-4B-Preview-GGUF",
            Modality::UiGeneration,
            Some("models/llm/UIGEN-FX-4B-Preview.Q4_K_M.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::LlamaCppEmbedded,
            &[RuntimeKind::MistralRsEmbedded, RuntimeKind::CandleEmbedded],
            &[ConversionLane::Gguf],
            10 * 1024 * 1024 * 1024,
            Some("Q4_K_M"),
            Some("apache-2.0"),
            true,
            false,
            false,
            &[
                "ui", "uigen", "frontend", "html", "css", "tailwind", "shadcn",
            ],
        ),
        manifest(
            "moonshine-tiny",
            "Moonshine Tiny",
            "Moonshine",
            "onnx-community/moonshine-tiny-ONNX",
            Modality::SpeechToText,
            Some("models/stt/encoder_model.onnx"),
            ArtifactFormat::Onnx,
            RuntimeKind::OnnxRuntimeEmbedded,
            &[RuntimeKind::SherpaOnnxEmbedded],
            &[ConversionLane::Onnx],
            2 * 1024 * 1024 * 1024,
            None,
            Some("apache-2.0"),
            true,
            false,
            false,
            &["stt", "edge"],
        ),
        manifest(
            "parakeet-tdt-0.6b-v3-int8",
            "Parakeet TDT 0.6B v3 INT8",
            "NVIDIA Parakeet",
            "csukuangfj/sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8",
            Modality::SpeechToText,
            Some("models/stt/parakeet-tdt-0.6b-v3-int8/encoder.int8.onnx"),
            ArtifactFormat::Onnx,
            RuntimeKind::SherpaOnnxEmbedded,
            &[RuntimeKind::OnnxRuntimeEmbedded],
            &[],
            4 * 1024 * 1024 * 1024,
            Some("INT8"),
            Some("cc-by-4.0"),
            true,
            false,
            false,
            &["stt", "nvidia", "parakeet", "quality", "cpu-ok"],
        ),
        manifest(
            "nemotron-speech-streaming-en-0.6b-int8",
            "Nemotron Speech Streaming EN 0.6B INT8",
            "NVIDIA Nemotron Speech",
            "nvidia/nemotron-speech-streaming-en-0.6b",
            Modality::SpeechToText,
            Some("models/stt/nemotron-speech-streaming-en-0.6b-int8/encoder.int8.onnx"),
            ArtifactFormat::Onnx,
            RuntimeKind::SherpaOnnxEmbedded,
            &[RuntimeKind::OnnxRuntimeEmbedded],
            &[],
            4 * 1024 * 1024 * 1024,
            Some("INT8"),
            Some("nvidia-open-model-license"),
            true,
            false,
            false,
            &[
                "stt",
                "nvidia",
                "nemotron",
                "streaming",
                "english",
                "performance",
            ],
        ),
        manifest(
            "kokoro-int8",
            "Kokoro INT8",
            "Kokoro",
            "hexgrad/Kokoro-82M",
            Modality::TextToSpeech,
            Some("models/tts/kokoro-v1.0.int8.onnx"),
            ArtifactFormat::Onnx,
            RuntimeKind::OnnxRuntimeEmbedded,
            &[RuntimeKind::SherpaOnnxEmbedded],
            &[ConversionLane::Onnx],
            3 * 1024 * 1024 * 1024,
            Some("INT8"),
            Some("apache-2.0"),
            true,
            false,
            false,
            &["tts", "edge"],
        ),
        manifest(
            "glm-ocr",
            "GLM OCR",
            "GLM OCR",
            "THUDM/GLM-OCR",
            Modality::Ocr,
            Some("models/ocr/GLM-OCR.Q4_K_M.gguf"),
            ArtifactFormat::Gguf,
            RuntimeKind::PythonWorker,
            &[RuntimeKind::LlamaCppEmbedded],
            &[ConversionLane::Gguf],
            10 * 1024 * 1024 * 1024,
            Some("Q4_K_M"),
            Some("glm"),
            true,
            false,
            false,
            &["ocr", "vision"],
        ),
        manifest(
            "harper-grammar",
            "Harper Grammar",
            "Harper",
            "Automattic/harper",
            Modality::Grammar,
            None,
            ArtifactFormat::Binary,
            RuntimeKind::HarperCoreEmbedded,
            &[],
            &[],
            512 * 1024 * 1024,
            None,
            Some("apache-2.0"),
            true,
            false,
            false,
            &["grammar", "typing"],
        ),
        manifest(
            "sd-turbo",
            "SD-Turbo",
            "Stable Diffusion",
            "stabilityai/sd-turbo",
            Modality::ImageGeneration,
            None,
            ArtifactFormat::Safetensors,
            RuntimeKind::StableDiffusionCppSubprocess,
            &[RuntimeKind::CandleEmbedded],
            &[ConversionLane::NativeSafetensors],
            16 * 1024 * 1024 * 1024,
            None,
            Some("openrail++"),
            true,
            false,
            false,
            &["image", "mid-tier"],
        ),
        manifest(
            "wan2.1-14b",
            "Wan2.1 14B 720P",
            "Wan2.1",
            "Wan-AI/Wan2.1-FLF2V-14B-720P",
            Modality::VideoGeneration,
            None,
            ArtifactFormat::Safetensors,
            RuntimeKind::StableDiffusionCppSubprocess,
            &[RuntimeKind::CandleEmbedded],
            &[ConversionLane::NativeSafetensors],
            32 * 1024 * 1024 * 1024,
            None,
            None,
            false,
            true,
            true,
            &["video", "high-end"],
        ),
    ]
}

pub fn default_activation_config() -> ActivationConfig {
    ActivationConfig {
        wake_words: detect_wake_words(),
        push_to_talk: KeyboardShortcut {
            modifiers: vec![],
            key: "Return".to_string(),
        },
        hands_free_toggle: KeyboardShortcut {
            modifiers: vec!["ControlLeft".to_string(), "ShiftLeft".to_string()],
            key: "Space".to_string(),
        },
    }
}

pub fn detect_wake_words() -> Vec<WakeWordConfigItem> {
    let wake_dir = Path::new("models/wake_words");

    WAKE_COMMAND_DEFINITIONS
        .into_iter()
        .filter_map(|definition| {
            let model_path = wake_dir.join(definition.model_filename);
            model_path.exists().then(|| WakeWordConfigItem {
                command_key: definition.command_key.to_string(),
                phrase: definition.phrase.to_string(),
                model_path: model_path.to_string_lossy().into_owned(),
                threshold: definition.threshold,
                aliases: definition
                    .aliases
                    .iter()
                    .map(|alias| (*alias).to_string())
                    .collect(),
            })
        })
        .collect()
}
