// Background names matching C++ exactly
pub const BACKGROUNDS: &[&str] = &[
    "Cubes",
    "Spring",
    "Summer",
    "Autumn",
    "Winter",
    "Seasonal Landscape 1",
    "Seasonal Landscape 2",
    "Newspaper",
    "Cartoon Cottage",
    "Anime girl",
    "Progressbar",
];

// Background credits matching C++ exactly
pub const BACKGROUND_CREDITS: &[&str] = &[
    "Photo credit: \"Cubes\" by Lernert & Sander",
    "Photo generated by OpenAI's Sora",
    "Photo generated by OpenAI's Sora",
    "Photo generated by OpenAI's Sora",
    "Photo generated by OpenAI's Sora",
    "Photo generated by OpenAI's Sora",
    "Photo generated by OpenAI's Sora",
    "Photo generated by OpenAI's Sora",
    "Photo generated by OpenAI's Sora",
    "Photo generated by OpenAI's Sora",
    "",
];

// Background file paths (relative to liquid-glass-rust directory)
pub const BACKGROUND_PATHS: &[&str] = &[
    "assets/textures/background-cubes.jpg",
    "assets/textures/background-spring.png",
    "assets/textures/background-summer.png",
    "assets/textures/background-autumn.png",
    "assets/textures/background-winter.png",
    "assets/textures/Seasonal Landscape 1.png",
    "assets/textures/Seasonal Landscape 2.png",
    "assets/textures/Newspaper.png",
    "assets/textures/Cartoon Cottage.png",
    "assets/textures/anime.png",
    "assets/textures/background-progress-bar.jpg",
];

/// All liquid glass parameters — matches the C++ ImGui controls exactly.
#[derive(Debug, Clone)]
pub struct UiState {
    // ── Shape ──
    pub power_factor: f32, // Superellipse power: 2=ellipse, 4=squircle, ∞=rect
    pub width: f32,        // Glass quad width (world units → pixels via scale)
    pub height: f32,       // Glass quad height

    // ── Distortion f(x) parameters ──
    pub a: f32, // f(x) = 1 - b * (c*e)^(-d*x-a)
    pub b: f32,
    pub c: f32,
    pub d: f32,
    pub f_power: f32, // Distortion power

    // ── Appearance ──
    pub noise: f32,       // Surface noise intensity
    pub glow_weight: f32, // Glow strength
    pub glow_edge0: f32,  // Glow smoothstep inner edge
    pub glow_edge1: f32,  // Glow smoothstep outer edge
    pub glow_bias: f32,   // Glow additive bias

    // ── Chromatic Aberration (Apple Liquid Glass effect) ──
    pub chromatic_aberration: f32, // Color separation strength
    pub aberration_samples: i32,   // Number of samples for quality

    // ── Blur ──
    pub blur_radius: f32,     // Blur kernel radius (pixels)
    pub blur_iterations: u32, // Multi-pass blur iteration count
    pub blur_downscale: f32,  // Blur downscale factor

    // ── Interaction ──
    pub mouse_control: bool,       // Glass follows mouse?
    pub position: [f32; 2],        // Glass center position (pixels)
    pub pixel_scale: f32,          // World-to-pixel scale factor
    pub camera_position: [f32; 2], // Camera position (world units)
    pub velocity: f32,             // Movement speed
    pub camera_velocity: f32,      // Camera movement speed

    // ── Background ──
    pub current_bg: usize,

    // ── Glass Material Variant ──
    pub glass_variant: usize, // Index into GLASS_VARIANTS
}

// Glass material variant names (from useless-electron-inspiration)
pub const GLASS_VARIANTS: &[&str] = &[
    "Regular",
    "Clear",
    "Dock",
    "App Icons",
    "Widgets",
    "Text",
    "AVPlayer",
    "FaceTime",
    "Control Center",
    "Notification Center",
    "Monogram",
    "Bubbles",
    "Identity",
    "Focus Border",
    "Focus Platter",
    "Keyboard",
    "Sidebar",
    "Abutted Sidebar",
    "Inspector",
    "Control",
    "Loupe",
    "Slider",
    "Camera",
    "Cartouche Popover",
];

// Preset sizes for different glass variants (width, height in world units)
pub const GLASS_VARIANT_SIZES: &[(f32, f32)] = &[
    (3.5, 3.5), // Regular - default
    (3.5, 3.5), // Clear
    (8.0, 0.8), // Dock - wide and short
    (1.2, 1.2), // App Icons - small square
    (4.0, 4.0), // Widgets - medium square
    (6.0, 1.0), // Text - wide and short
    (6.0, 4.0), // AVPlayer - video aspect
    (5.0, 5.0), // FaceTime - square
    (3.0, 6.0), // Control Center - tall
    (3.0, 7.0), // Notification Center - tall
    (1.5, 1.5), // Monogram - small
    (2.0, 2.0), // Bubbles - small
    (2.5, 2.5), // Identity - small
    (4.0, 4.0), // Focus Border - medium
    (3.0, 1.5), // Focus Platter - wide
    (8.0, 3.0), // Keyboard - wide
    (2.5, 8.0), // Sidebar - tall and narrow
    (2.5, 8.0), // Abutted Sidebar - tall and narrow
    (3.0, 5.0), // Inspector - tall
    (2.0, 2.0), // Control - small
    (2.0, 2.0), // Loupe - small
    (5.0, 0.5), // Slider - very wide and short
    (4.0, 3.0), // Camera - medium
    (3.0, 2.0), // Cartouche Popover - medium
];

impl Default for UiState {
    fn default() -> Self {
        Self {
            // Matches C++ defaults exactly
            power_factor: 3.0,
            width: 3.5,
            height: 3.5,

            a: 0.7,
            b: 2.3,
            c: 5.2,
            d: 6.9,
            f_power: 1.0,

            noise: 0.06,
            glow_weight: 0.25,
            glow_edge0: 0.5,
            glow_edge1: -0.5,
            glow_bias: 0.0,

            chromatic_aberration: 0.008, // Increased for more solid effect
            aberration_samples: 5,       // Higher quality for smoother edges

            blur_radius: 2.0,
            blur_iterations: 1,
            blur_downscale: 0.5,

            mouse_control: false,
            position: [400.0, 300.0],
            pixel_scale: 100.0, // 1 world unit = 100 pixels
            camera_position: [0.0, 0.0],
            velocity: 2.0,
            camera_velocity: 2.0,

            current_bg: 0,
            glass_variant: 0, // Regular
        }
    }
}

impl UiState {
    /// Glass width in pixels
    pub fn glass_width_px(&self) -> f32 {
        self.width * self.pixel_scale
    }

    /// Glass height in pixels
    pub fn glass_height_px(&self) -> f32 {
        self.height * self.pixel_scale
    }

    /// Apply preset size for current glass variant
    pub fn apply_variant_size(&mut self) {
        let (w, h) = GLASS_VARIANT_SIZES[self.glass_variant];
        self.width = w;
        self.height = h;
    }
}
