import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

const read = (path: string) => readFileSync(path, "utf8");
const lineCount = (path: string) => read(path).split(/\r?\n/).length;

test("DX launch readiness keeps packet IO, JSON helpers, and review helpers focused", () => {
  const parentPath = "crates/agent_ui/src/dx_launch_readiness.rs";
  const fieldsPath = "crates/agent_ui/src/dx_launch_readiness/packet_fields.rs";
  const packetsPath = "crates/agent_ui/src/dx_launch_readiness/packets.rs";
  const reviewPath = "crates/agent_ui/src/dx_launch_readiness/review.rs";
  const examplesPath = "crates/agent_ui/src/dx_launch_readiness/examples.rs";
  const statusCountsPath = "crates/agent_ui/src/dx_launch_readiness/status_counts.rs";

  assert.ok(existsSync(fieldsPath), "missing focused launch-readiness packet field module");
  assert.ok(existsSync(packetsPath), "missing focused launch-readiness packet IO module");
  assert.ok(existsSync(reviewPath), "missing focused launch-readiness review policy module");
  assert.ok(existsSync(examplesPath), "missing focused launch-readiness example helper module");
  assert.ok(existsSync(statusCountsPath), "missing focused launch-readiness status count module");

  const parent = read(parentPath);
  const fields = read(fieldsPath);
  const packets = read(packetsPath);
  const review = read(reviewPath);
  const examples = read(examplesPath);
  const statusCounts = read(statusCountsPath);

  assert.match(parent, /^mod examples;$/m);
  assert.match(parent, /^mod packet_fields;$/m);
  assert.match(parent, /^mod packets;$/m);
  assert.match(parent, /^mod review;$/m);
  assert.match(parent, /^mod status_counts;$/m);
  assert.match(parent, /use self::examples::\{balanced_examples, push_recovery_commands, push_unique\};/);
  assert.match(parent, /use self::packet_fields::\{\s*bool_field, packet_status, pointer_string, pointer_usize, string_field, usize_field,\s*\};/);
  assert.match(parent, /use self::packets::read_checked_packet;/);
  assert.match(parent, /use self::review::\{command_fanout_count, redaction_requires_review\};/);
  assert.doesNotMatch(parent, /fn read_checked_packet\(/);
  assert.doesNotMatch(parent, /fn read_json_packet\(/);
  assert.doesNotMatch(parent, /fn packet_status\(/);
  assert.doesNotMatch(parent, /fn push_recovery_commands\(/);
  assert.doesNotMatch(parent, /fn command_fanout_count\(/);
  assert.match(parent, /const MAX_PACKET_LABEL_CHARS: usize = \d+;/);
  assert.match(parent, /const MAX_PACKET_STATUS_CHARS: usize = \d+;/);
  assert.match(parent, /const MAX_PACKET_STATE_CHARS: usize = \d+;/);
  assert.match(parent, /const MAX_PACKET_DETAIL_CHARS: usize = \d+;/);
  assert.match(parent, /const MAX_PACKET_ACTION_CHARS: usize = \d+;/);
  assert.match(parent, /fn compact_packet_text\(raw: &str, max_chars: usize\) -> Option<String>/);
  assert.match(parent, /fn compact_packet_option\(raw: Option<&str>, max_chars: usize\) -> Option<String>/);
  assert.match(parent, /fn compact_packet_list\(values: Vec<String>, max_chars: usize\) -> Vec<String>/);
  assert.match(parent, /fn compact_snapshot_display_strings\(snapshot: &mut DxLaunchReadinessSnapshot\)/);
  assert.match(parent, /compact_snapshot_display_strings\(&mut snapshot\);\s+snapshot\.examples = balanced_examples\(&snapshot\.examples\);/);
  assert.match(parent, /let raw_status = packet_status\(packet\);/);
  assert.match(parent, /record\(&raw_status\);/);
  assert.match(parent, /compact_packet_text\(&raw_status, MAX_PACKET_STATUS_CHARS\)/);
  assert.match(parent, /compact_packet_text\(&format!\("Import \{file_name\}"\), MAX_PACKET_LABEL_CHARS\)/);
  assert.match(parent, /compact_packet_text\(&format!\("Gate \{file_name\}"\), MAX_PACKET_LABEL_CHARS\)/);
  assert.match(parent, /compact_packet_text\(&format!\("Fallback \{file_name\}"\), MAX_PACKET_LABEL_CHARS\)/);
  assert.match(parent, /compact_packet_text\(\s*pointer_string\(packet, "\/freshness_policy\/latest_freshness_state"\)\.unwrap_or\("unknown"\),\s*MAX_PACKET_STATE_CHARS,\s*\)/);
  assert.match(parent, /compact_packet_text\(\s*pointer_string\(packet, "\/latest_status_receipt\/freshness_state"\)\.unwrap_or\("unknown"\),\s*MAX_PACKET_STATE_CHARS,\s*\)/);
  assert.match(parent, /compact_packet_text\(\s*string_field\(packet, "active_receipt_state"\)\.unwrap_or\("unknown"\),\s*MAX_PACKET_STATE_CHARS,\s*\)/);
  assert.match(parent, /compact_packet_option\(string_field\(packet, "next_action"\), MAX_PACKET_ACTION_CHARS\)/);
  assert.match(parent, /snapshot\.recovery_commands = compact_packet_list\(\s*std::mem::take\(&mut snapshot\.recovery_commands\),\s*MAX_PACKET_ACTION_CHARS,\s*\);/);
  assert.doesNotMatch(parent, /string_field\(packet, "next_action"\)\.map\(ToString::to_string\)/);
  assert.doesNotMatch(parent, /pointer_string\(packet, "\/freshness_policy\/latest_freshness_state"\)\s*\.unwrap_or\("unknown"\)\s*\.to_string\(\)/);
  assert.doesNotMatch(parent, /pointer_string\(packet, "\/latest_status_receipt\/freshness_state"\)\s*\.unwrap_or\("unknown"\)\s*\.to_string\(\)/);
  assert.doesNotMatch(parent, /string_field\(packet, "active_receipt_state"\)\s*\.unwrap_or\("unknown"\)\s*\.to_string\(\)/);
  assert.match(fields, /pub\(super\) fn packet_status/);
  assert.match(fields, /pub\(super\) fn pointer_usize/);
  assert.match(packets, /pub\(super\) fn read_checked_packet/);
  assert.match(packets, /MAX_PACKET_BYTES/);
  assert.match(packets, /\.take\(MAX_PACKET_BYTES \+ 1\)/);
  assert.match(packets, /read_to_end\(&mut buffer\)/);
  assert.match(packets, /buffer\.len\(\) as u64 > MAX_PACKET_BYTES/);
  assert.match(packets, /serde_json::from_slice\(&buffer\)/);
  assert.doesNotMatch(packets, /read_to_string/);
  assert.doesNotMatch(packets, /serde_json::from_str/);
  assert.match(review, /pub\(super\) fn command_fanout_count/);
  assert.match(review, /exports_secret_values/);
  assert.match(examples, /pub\(super\) fn balanced_examples/);
  assert.match(examples, /pub\(super\) fn push_recovery_commands/);
  assert.match(statusCounts, /impl DxLaunchReadinessStatusCounts/);
  assert.match(statusCounts, /pub\(super\) fn record/);

  assert.ok(lineCount(parentPath) < 430, "dx_launch_readiness.rs should stay focused on snapshot assembly and display bounds");
  assert.ok(lineCount(fieldsPath) < 75, "launch-readiness packet field module should stay small");
  assert.ok(lineCount(packetsPath) < 65, "launch-readiness packet IO module should stay small");
  assert.ok(lineCount(reviewPath) < 70, "launch-readiness review policy module should stay small");
  assert.ok(lineCount(examplesPath) < 80, "launch-readiness example helper module should stay small");
  assert.ok(lineCount(statusCountsPath) < 35, "launch-readiness status count module should stay small");
});
