#[derive(Clone, Copy, Eq, PartialEq)]
pub(super) enum ReadinessKind {
    Doc,
    Contract,
    Fixture,
    Artifact,
}

pub(super) struct ExpectedReadinessFile {
    pub(super) label: &'static str,
    pub(super) relative_path: &'static str,
    pub(super) kind: ReadinessKind,
    pub(super) marker: Option<&'static str>,
}

pub(super) const EXPECTED_STYLE_FILES: &[ExpectedReadinessFile] = &[
    ExpectedReadinessFile {
        label: "Cargo manifest",
        relative_path: "Cargo.toml",
        kind: ReadinessKind::Doc,
        marker: Some(r#"name = "dx-style""#),
    },
    ExpectedReadinessFile {
        label: "Public workflow docs",
        relative_path: "README.md",
        kind: ReadinessKind::Doc,
        marker: Some("dx style build"),
    },
    ExpectedReadinessFile {
        label: "Style panel plan",
        relative_path: "PLAN.md",
        kind: ReadinessKind::Doc,
        marker: Some("Zed Style Right Panel"),
    },
    ExpectedReadinessFile {
        label: "Compatibility table",
        relative_path: "TAILWIND_COMPATIBILITY.md",
        kind: ReadinessKind::Doc,
        marker: Some("tailwindcss@4.3.0"),
    },
    ExpectedReadinessFile {
        label: "Contract changelog",
        relative_path: "CHANGELOG.md",
        kind: ReadinessKind::Doc,
        marker: Some("Group two-way contract metadata"),
    },
    ExpectedReadinessFile {
        label: "Grouped class contract",
        relative_path: "src/core/engine/grouped_class_contract.rs",
        kind: ReadinessKind::Contract,
        marker: Some("GROUPED_CLASS_CONTRACT_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Grouped class editor read model",
        relative_path: "src/core/engine/grouped_class_read_model.rs",
        kind: ReadinessKind::Contract,
        marker: Some("GroupedClassDryRunPatchPreview"),
    },
    ExpectedReadinessFile {
        label: "Grouped class cursor context",
        relative_path: "src/core/engine/grouped_class_cursor_context.rs",
        kind: ReadinessKind::Contract,
        marker: Some("GROUPED_CLASS_CURSOR_CONTEXT_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Grouped class dry-run receipt",
        relative_path: "src/core/engine/grouped_class_dry_run_receipt.rs",
        kind: ReadinessKind::Contract,
        marker: Some("GROUPED_CLASS_DRY_RUN_RECEIPT_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Grouped class editor write bridge",
        relative_path: "src/core/engine/grouped_class_editor_write_bridge.rs",
        kind: ReadinessKind::Contract,
        marker: Some("GROUPED_CLASS_EDITOR_WRITE_BRIDGE_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Grouped class source apply contract",
        relative_path: "src/core/engine/grouped_class_source_apply.rs",
        kind: ReadinessKind::Contract,
        marker: Some("GROUPED_CLASS_SOURCE_APPLY_CONTRACT_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Grouped class Web Preview context",
        relative_path: "src/core/engine/grouped_class_web_preview_context.rs",
        kind: ReadinessKind::Contract,
        marker: Some("GROUPED_CLASS_WEB_PREVIEW_CONTEXT_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Grouped class registry receipt",
        relative_path: "src/core/engine/grouped_class_registry_receipt.rs",
        kind: ReadinessKind::Contract,
        marker: Some("GROUPED_CLASS_REGISTRY_RECEIPT_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Grouped class reverse CSS map",
        relative_path: "src/core/engine/grouped_class_reverse_css_map.rs",
        kind: ReadinessKind::Contract,
        marker: Some("GROUPED_CLASS_REVERSE_CSS_MAP_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Grouped class reverse CSS delta",
        relative_path: "src/core/engine/grouped_class_reverse_css_delta.rs",
        kind: ReadinessKind::Contract,
        marker: Some("GROUPED_CLASS_REVERSE_CSS_DELTA_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Visual generator catalog",
        relative_path: "src/core/engine/visual_generator_catalog.rs",
        kind: ReadinessKind::Contract,
        marker: Some("VISUAL_GENERATOR_CATALOG_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Visual generator recipe catalog",
        relative_path: "src/core/engine/visual_generator_recipe_catalog.rs",
        kind: ReadinessKind::Contract,
        marker: Some("VISUAL_GENERATOR_RECIPE_CATALOG_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Visual generator control catalog",
        relative_path: "src/core/engine/visual_generator_control_catalog.rs",
        kind: ReadinessKind::Contract,
        marker: Some("VISUAL_GENERATOR_CONTROL_CATALOG_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Visual generator CSS hint catalog",
        relative_path: "src/core/engine/visual_generator_css_hint_catalog.rs",
        kind: ReadinessKind::Contract,
        marker: Some("VISUAL_GENERATOR_CSS_HINT_CATALOG_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "CSS declaration dry-run contract",
        relative_path: "src/core/engine/css_declaration_dry_run.rs",
        kind: ReadinessKind::Contract,
        marker: Some("CSS_DECLARATION_DRY_RUN_CONTRACT_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Browser compat contract",
        relative_path: "src/core/engine/browser_compat.rs",
        kind: ReadinessKind::Contract,
        marker: Some("TAILWIND_POSTCSS_BROWSER_COMPAT_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Directive ledger",
        relative_path: "src/core/engine/directive_ledger.rs",
        kind: ReadinessKind::Contract,
        marker: Some("TAILWIND_V43_CSS_DIRECTIVE_LEDGER_SCHEMA"),
    },
    ExpectedReadinessFile {
        label: "Utility ledger",
        relative_path: "src/core/engine/utility_ledger.rs",
        kind: ReadinessKind::Contract,
        marker: Some("full_value_modifier_parity_proven"),
    },
    ExpectedReadinessFile {
        label: "Registry snapshot plan",
        relative_path: "src/cache/registry_snapshot_plan.rs",
        kind: ReadinessKind::Contract,
        marker: Some("REGISTRY_SNAPSHOT_PATH"),
    },
    ExpectedReadinessFile {
        label: "Tailwind fixture matrix",
        relative_path: "fixtures/tailwind-v43-official-fixture-matrix.json",
        kind: ReadinessKind::Fixture,
        marker: None,
    },
    ExpectedReadinessFile {
        label: "Tailwind fixture inventory",
        relative_path: "fixtures/tailwind-v43-official-candidate-inventory.json",
        kind: ReadinessKind::Fixture,
        marker: None,
    },
    ExpectedReadinessFile {
        label: "Browser compat fixture",
        relative_path: "fixtures/tailwind-postcss-browser-compat.json",
        kind: ReadinessKind::Fixture,
        marker: None,
    },
    ExpectedReadinessFile {
        label: "Visual generator catalog fixture",
        relative_path: "fixtures/visual-generator-catalog.json",
        kind: ReadinessKind::Fixture,
        marker: Some("dx.style.visual-generator-catalog"),
    },
    ExpectedReadinessFile {
        label: "PostCSS compat matrix",
        relative_path: "fixtures/postcss-compat-matrix.json",
        kind: ReadinessKind::Fixture,
        marker: None,
    },
    ExpectedReadinessFile {
        label: "Equal-output canary",
        relative_path: "fixtures/tailwind-equal-output-canary.json",
        kind: ReadinessKind::Fixture,
        marker: None,
    },
    ExpectedReadinessFile {
        label: "Editor write bridge preflight fixture",
        relative_path: "fixtures/grouped-class-editor-write-bridge-preflight.json",
        kind: ReadinessKind::Fixture,
        marker: Some("dx.style.grouped-class-editor-write-bridge-preflight"),
    },
    ExpectedReadinessFile {
        label: "Source apply contract fixture",
        relative_path: "fixtures/grouped-class-source-apply-contract.json",
        kind: ReadinessKind::Fixture,
        marker: Some("dx.style.grouped-class-source-apply-contract"),
    },
    ExpectedReadinessFile {
        label: "Grouped class Web Preview context fixture",
        relative_path: "fixtures/grouped-class-web-preview-context.json",
        kind: ReadinessKind::Fixture,
        marker: Some("dx.style.grouped-class-web-preview-context"),
    },
    ExpectedReadinessFile {
        label: "Grouped class registry receipt fixture",
        relative_path: "fixtures/grouped-class-registry-receipt.json",
        kind: ReadinessKind::Fixture,
        marker: Some("dx.style.grouped-class-registry-receipt"),
    },
    ExpectedReadinessFile {
        label: "Grouped class reverse CSS map fixture",
        relative_path: "fixtures/grouped-class-reverse-css-map.json",
        kind: ReadinessKind::Fixture,
        marker: Some("dx.style.grouped-class-reverse-css-map"),
    },
    ExpectedReadinessFile {
        label: "Grouped class reverse CSS delta fixture",
        relative_path: "fixtures/grouped-class-reverse-css-delta-contract.json",
        kind: ReadinessKind::Fixture,
        marker: Some("dx.style.grouped-class-reverse-css-delta-contract"),
    },
    ExpectedReadinessFile {
        label: "Visual generator recipe fixture",
        relative_path: "fixtures/visual-generator-recipe-catalog.json",
        kind: ReadinessKind::Fixture,
        marker: Some("dx.style.visual-generator-recipe-catalog"),
    },
    ExpectedReadinessFile {
        label: "Visual generator control fixture",
        relative_path: "fixtures/visual-generator-control-catalog.json",
        kind: ReadinessKind::Fixture,
        marker: Some("dx.style.visual-generator-control-catalog"),
    },
    ExpectedReadinessFile {
        label: "Visual generator CSS hint fixture",
        relative_path: "fixtures/visual-generator-css-declaration-hint-catalog.json",
        kind: ReadinessKind::Fixture,
        marker: Some("dx.style.visual-generator-css-declaration-hint-catalog"),
    },
    ExpectedReadinessFile {
        label: "CSS declaration dry-run fixture",
        relative_path: "fixtures/css-declaration-dry-run-contract.json",
        kind: ReadinessKind::Fixture,
        marker: Some("dx.style.css-declaration-dry-run-contract"),
    },
    ExpectedReadinessFile {
        label: "Demo CSS",
        relative_path: "style.css",
        kind: ReadinessKind::Artifact,
        marker: Some(":root"),
    },
    ExpectedReadinessFile {
        label: "Internal style.dxm",
        relative_path: ".dx/style/style.dxm",
        kind: ReadinessKind::Artifact,
        marker: None,
    },
];
