use std::path::PathBuf;

#[derive(Clone)]
pub(crate) struct DxLaunchSourceAuditSnapshot {
    pub root: PathBuf,
    pub latest_path: PathBuf,
    pub markdown_path: PathBuf,
    pub dx_studio_qa_path: PathBuf,
    pub root_exists: bool,
    pub latest_present: bool,
    pub markdown_present: bool,
    pub dx_studio_qa_present: bool,
    pub schema_valid: bool,
    pub status: String,
    pub operator_summary: String,
    pub generated_at: String,
    pub mode: String,
    pub score: usize,
    pub passed: bool,
    pub ready_for_commit_coordination: bool,
    pub next_target: String,
    pub repo_count: usize,
    pub active_output_count: usize,
    pub source_clean_count: usize,
    pub risk_review_count: usize,
    pub owner_review_count: usize,
    pub diff_check_failure_count: usize,
    pub template_trust_passed: bool,
    pub template_roots_scanned: usize,
    pub template_roots_total: usize,
    pub template_node_modules_found: usize,
    pub dx_studio_score: usize,
    pub dx_studio_passed: bool,
    pub dx_studio_passed_checks: usize,
    pub dx_studio_total_checks: usize,
    pub repo_rows: Vec<String>,
    pub blocker_rows: Vec<String>,
    pub delta_rows: Vec<String>,
    pub first_issue: Option<String>,
    pub last_error: Option<String>,
}
